Fix compile error in Kilted
In Kilted, rclcpp::get_typesupport_handle() was removed after being
deprecated (https://github.com/ros2/rclcpp/pull/2209) and the build
fails with:

    ros2_helpers.hpp:60:15: error: 'get_typesupport_handle' is not a member of 'rclcpp'

The function was replaced with rclcpp::get_message_typesupport_handle()
in Jazzy and Kilted, but not in Humble. Therefore, we detect Humble in
CMake and keep using the old name in Humble. All newer distros use the
new name.